config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  resources :portfolios, except: [:show]

  get 'angular-items', to: 'portfolios#angular'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'
  
  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  
  resources :blogs do 
    member do
      get :toggle_status
    end
  end

  root to: 'pages#home'
end

app/views/shared/_application_footer.html.erb
<div class="mt-auto text-white-50">
  <p class="app-footer"><%= @copyright %></p>
</div>

app/views/shared/_application_nav.erb
<header class="mb-auto">
  <div>
    <h3 class="float-md-start mb-0">Dev Portfolio</h3>
    <nav class="nav nav-masthead justify-content-center float-md-end">
      <%= link_to "Home", root_path, class: 'nav-link' %>
      <%= link_to "About Me", about_me_path, class: 'nav-link' %>
      <%= link_to "Contact", contact_path, class: 'nav-link' %>
      <%= link_to "Blog", blogs_path, class: 'nav-link' %>
      <%= link_to "Portfolio", portfolios_path, class: 'nav-link' %>
      <%#= button_to "Logout", destroy_user_session_path, method: :delete, class: 'nav-link btn btn-danger btn-sm' %>
    </nav>
  </div>
</header>

app/views/shared/_application_nav.html.erb
<div class="mb-auto">
  <div>
    <h3 class="float-md-start mb-0">Dev Portfolio</h3>
    <nav class="nav nav-masthead justify-content-center float-md-end app-nav">
      <%= nav_helper 'nav-link', 'span' %>
      <%= login_helper 'nav-link' %>
    </nav>
  </div>
</div>

app/views/shared/_blog_footer.html.erb
<footer class="blog-footer">
  <p><%= @copyright %></p>
  <p>
    <a href="#">Back to top</a>
  </p>
</footer>

app/views/shared/_blog_header.html.erb
<header class="blog-header py-3">
  <div class="row flex-nowrap justify-content-start align-items-center">
    <div class="col-6 d-flex justify-content-start ml-0 auto">
      <h2>My Blog</h2>
    </div>
    <div class="col-6 d-flex justify-content-end ">
      <%= login_helper 'nav-link' %>
    </div>
  </div>
</header>

app/views/shared/_blog_nav.html.erb
<div class="nav-tabs mb-2">
  <nav class="nav d-flex justify-content-center blog-nav">
    <%= nav_helper 'nav-link', 'span' %>
  </nav>
</div>

app/views/shared/_blog_sidebar.html.erb
<div class="col-md-4">
  <div class="position-sticky" style="top: 2rem;">
    <div class="p-4 mb-3 bg-light rounded">
      <h4 class="fst-italic">About</h4>
      <p class="mb-0">
        It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.
      </p>
    </div>

    <div class="p-4">
      <h4 class="fst-italic">Elsewhere</h4>
      <ol class="list-unstyled social-links">
      <li><a href="https://github.com/parthsoni262/parth-portfolio"><%= fa_icon "github" %></a></li>
      <li><a href="https://twitter.com/parth_soni_01"><%= fa_icon "twitter" %></a></li>
      <li><a href="#"><%= fa_icon "instagram" %></a></li>
      <li><a href="#"><%= fa_icon "facebook" %></a></li>
    </ol>
    </div>
  </div>
</div>

app/views/shared/_nav.html.erb
<div class="<%= location %>">
  <div><%= link_to "Home", root_path %></div>
  <div><%= link_to "About Me", about_me_path %></div>
  <div><%= link_to "Contact", contact_path %></div>
  <div><%= link_to "Blog", blogs_path %></div>
  <div><%= link_to "Portfolio", portfolios_path %></div>
</div>

app/views/shared/_portfolio_footer.html.erb
<footer class="text-muted py-5">
  <div class="container">
    <p class="float-end mb-1">
  	  <%= link_to "View All Portfolio Items", portfolios_path %> | 
      <a href="#">Back to top</a>
    </p>
    <p class="mb-1"><%= @copyright %></p>
  </div>
</footer>

app/views/shared/_portfolio_header.html.erb
<div>
  <section class="jumbotron text-center">
    <div class="container">
      <h1 class="jumbotron-heading">My Portfolio</h1>
      <p class="lead text-muted">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
      <p>
        <%= link_to "Find Out More About Me", about_me_path, class: 'btn btn-primary' %>
        <%= link_to "My Blog", blogs_path, class: 'btn btn-secondary' %>
      </p>
    </div>
  </section>
</div>

app/views/shared/_portfolio_nav.html.erb
<div class=" bg-dark" id="navbarHeader">
  <div class="container">
    <div class="row">
      <div class="col-sm-8 col-md-7 py-4">
        <h4 class="text-white">About</h4>
        <p class="text-muted">App development refers to building, creating, and an maintaining websites. It includes aspects such as web design, web publishing, web programming, and database management. ... A web developer may be involved in designing a website.</p>
      </div>
      <div class="col-sm-4 offset-md-1 py-4">
        <h4 class="text-white">Explore</h4>
        <ul class="list-unstyled">
          <%= nav_helper 'text-white', 'li' %>
          <li><%= login_helper 'text-white' %></li>
        </ul>
      </div>
    </div>
  </div>
</div>
<div class="navbar navbar-dark bg-dark shadow-sm">
  <div class="container">
    <a href="#" class="navbar-brand d-flex align-items-center">
      <strong>Dev</strong>
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  </div>
</div>